bKProject/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import Email, Length, DataRequired, Regexp, EqualTo
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from app.models import User
from wtforms.validators import ValidationError
from flask import render_template
from wtforms import TextAreaField

class BlogForm(FlaskForm) :
    title = StringField(label='标题', validators=[
        DataRequired(message='标题必须填写'),
        Length(1, 32, message='长度必须是1-32')
    ])
    content = TextAreaField(label='正文', validators=[
        DataRequired(message='正文必须填写'),
        Length(20, 1024, message='长度必须是20-1024')
    ])
    submit = SubmitField(label='提交')

class CommentForm(FlaskForm) :
    content = TextAreaField(label='评论',validators=[
        Length(1, 200, message='长度必须是0-200')
    ])
    submit = SubmitField(label='发表')

class EditUserForm(FlaskForm) :
    name = StringField(label='昵称', validators=[
        DataRequired(message='必须填写昵称'),
        Length(1, 64, message='长度必须是1-64'),
    ])
    label= StringField(label='个性签名', validators=[
        Length(0, 128, message='长度必须是0-128')
    ])
    location = StringField(label='位置', validators=[])

    password = PasswordField(label='密码', validators=[
        Length(0, 64, message='长须必须是6-64'),
        Regexp('^.*$', 0, message='密码必须包含xxx')
    ])
    password_again = PasswordField(label='确认密码', validators=[
        EqualTo('password', message='两次输入密码不一致')
    ])
    submit = SubmitField(label='确认修改')

    #自定义校验方法
    def validate_name(self, field):
        if field.data == 'lizhiyong' :
            # 异常信息会被放到name的errors中
            raise ValidationError('你没资格用这个名字')

bKProject/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

bKProject/app/main/views.py
from . import main
from flask import render_template
from flask import session, request, make_response
from flask_login import login_required, current_user
from app.models import Permission
from app.decorator import permission_required
from .forms import EditUserForm
from app import db
from flask import redirect, url_for,abort
from .forms import BlogForm,CommentForm
from app.models import Blog,User,Comment,Collect
from wtforms.validators import ValidationError
from datetime import datetime,date

@main.route('/write_blog',methods=["GET","POST"])
@permission_required(Permission.WRITE)
def write_blog():
    form = BlogForm()
    if form.validate_on_submit():
        blog = Blog()
        blog.title = form.title.data
        blog.content = form.content.data
        blog.user=current_user
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('.index'))
    return render_template("main/write_blog.html",form = form)

@main.route('/follow')
@permission_required(Permission.FOLLOW)
def follow():
    user_id = request.args.get("user_id")
    if user_id is None:
        abort(404)
    user = User.query.get(user_id)
    if user is None:
        abort(404)
    current_user.follow(user)
    return redirect(url_for('.user_main_page',user_id=user_id))

@main.route('/unfollow')
@permission_required(Permission.FOLLOW)
def unfollow():
    user_id = request.args.get("user_id")
    if user_id is None:
        abort(404)
    user = User.query.get(user_id)
    if user is None:
        abort(404)
    current_user.unfollow(user)
    return redirect(url_for('.user_main_page',user_id=user_id))

@main.route('/comment',methods=["GET","POST"])
@permission_required(Permission.COMMENT)
def comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment()
        comment.content = form.content.data
        comment.user=current_user
        db.session.add(comment)
        db.session.commit()
        print(current_user.blogs)
        return redirect(url_for('.content',id=current_user.blogs.id))
    return render_template("main/comment.html",form=form)

@main.route('/blog_info')
@permission_required(Permission.READ)
def blog_info():
    blog_id = request.args.get("blog_id")
    if blog_id is None:
        abort(404)
    blog = Blog.query.get(blog_id)
    if blog is None:
        abort(404)
    return render_template("main/blog_info.html",b=blog)

@main.route('/edit_user',methods=["GET","POST"])
@login_required
def edit_user():
    form = EditUserForm()
    if form.validate_on_submit():
        current_user.name=form.name.data
        if len(form.password.data):
            current_user.password = form.password.data
        if len(form.label.data):
            current_user.label = form.label.data
        if len(form.location.data):
            current_user.location = form.location.data
        db.session.add(current_user)
        db.session.commit()
        return redirect(url_for("main.user_info"))
    form.name.data = current_user.name
    return render_template("main/edit_user.html",form=form)

@main.route('/index')
@permission_required(Permission.READ)
def index():
    page = request.args.get('page', type=int, default=1)
    pagination = Blog.query.order_by(Blog.id.desc()).paginate(page, 5, False)
    blogs = pagination.items
    b = Blog.query.all()
    t=date.today()
    d = Blog.query.filter(db.cast(Blog.time, db.DATE) == db.cast(t,db.DATE)).all()
    return render_template('main/index.html', pagination=pagination, blogs=blogs,b=len(b),d=len(d))

@main.route('/user_main_page')
def user_main_page():
    user_id=request.args.get("user_id")
    if user_id is None:
        abort(404)
    user=User.query.get(user_id)
    page = request.args.get("page",type=int,default=1)
    pagination = user.blogs.order_by(Blog.id.desc()).paginate(page, 5, False)
    return render_template('main/user_main_page.html', user=user, pagination=pagination)



@main.route('/user_info')
@login_required
def user_info():
    page = request.args.get("page",type=int,default=1)
    pagination = current_user.blogs.order_by(Blog.id.desc()).paginate(page, 5, False)
    return render_template("main/user_info.html",pagination=pagination)

@main.route('/collect')
@login_required
def collect():
    blog_id = request.args.get("blog_id")
    if blog_id is None:
        abort(404)
    blog = Blog.query.get(blog_id)
    if blog is None:
        abort(404)
    current_user.collect_blog(blog_id)
    return redirect(url_for('.blog_info',blog_id=blog_id))

@main.route('/mycollect')
@login_required
def mycollect():
    page = request.args.get('page', type=int, default=1)
    pagination  = current_user.collects.order_by(Collect.id.desc()).paginate(page, 5, False)
    collects = pagination.items
    c=Collect.query.filter_by(collector_id=current_user.id).all()
    for  i in c:
        print(i.id,i.blog_id)
    return render_template("main/collect.html",collects=collects,pagination=pagination)

bKProject/app/templates/main/blog_info.html
{% extends 'base.html' %}

{% block content %}
    <h1>欢迎<strong>{{current_user.name}}</strong></h1>

            <div class="list-group">
                  <a href="#" class="list-group-item ">
                    <h4 class="list-group-item-heading">
                        {{b.title}} <span style="float: right">{{b.user.name}}&nbsp;&nbsp;{{b.time}}</span>
                    </h4>
                    <p class="list-group-item-text">
                        <pre style="border-width: 0px;background: white">
                        {{b.content}}
                      </pre>
                    </p>
                  </a>
            </div>

            <div>
                <a href="{{url_for('main.collect', blog_id=b.id)}}" style="float: left" class="btn btn-danger">评论</a>
                <a href="{{url_for('main.collect', blog_id=b.id)}}" style="float: left" class="btn btn-danger">回复</a>
                <a href="{{url_for('main.collect', blog_id=b.id)}}" style="float: right" class="btn btn-danger">收藏</a>
            </div>

{% endblock %}

bKProject/app/templates/main/collect.html
{% extends 'base.html' %}

{% block content %}
    <h1>欢迎<strong>{{current_user.name}}的收藏</strong></h1>

            <div class="list-group">
                {% for c in collects %}
                  <ab href="#" class="list-group-item ">
                    <h4 class="list-group-item-heading">
                        <a href="#">{{c.blog_id.title}}</a>
                        <span style="float: right">
                        <a href="#"> #</a>

                        &nbsp;&nbsp;{{c.time}}</span>
                    </h4>
                  </ab>
                {% endfor %}
            </div>

        <div align="center">
            {% import 'page/macro.html' as macro %}
            {{macro.pagination_widget(pagination, 'main.collect')}}
        </div>

{% endblock %}

bKProject/app/templates/main/edit_user.html
{% extends 'base.html' %}
{% block content %}


    <div class="col-md-offset-3 col-md-6">
        <div style="border-bottom: 1px solid #d5d5d5">
            <form class="form-horizontal" method="post" action="">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <label class="col-md-3 control-label">{{form.name.label}}</label>
                    <div class="col-md-6">
                        {{form.name(class="form-control")}}
                        {% for e in form.name.errors %}
                            <span style="color: red">{{e}}</span>
                        {% endfor %}
                    </div>

                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">{{form.label.label}}</label>
                    <div class="col-md-6">
                        {{form.label(class="form-control")}}
                        {% for e in form.label.errors %}
                            <span style="color: red">{{e}}</span>
                        {% endfor %}
                    </div>

                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">{{form.location.label}}</label>
                    <div class="col-md-6">
                        {{form.location(class="form-control")}}
                        {% for e in form.location.errors %}
                            <span style="color: red">{{e}}</span>
                        {% endfor %}
                    </div>

                </div>
                <div class="form-group">
                    <label class="control-label col-md-3">{{form.password.label}}</label>
                    <div class="col-md-6">
                        {{form.password(class="form-control")}}
                        {% for e in form.password.errors %}
                            <span style="color: red">{{e}}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-3">{{form.password_again.label}}</label>
                    <div class="col-md-6">
                        {{form.password_again(class="form-control")}}
                        {% for e in form.password_again.errors %}
                            <span style="color: red">{{e}}</span>
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-4">
                        {{form.submit(class="btn btn-success")}}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

bKProject/app/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
    <h3>欢迎</h3><h1>{{current_user.name}}</h1>
            <ul class="list-group">
                <li class="list-group-item list-group-item-success">
                    总信息数：
                    <a class="">{{b}}</a>&nbsp;&nbsp;
                    今日发表：
                    <a class="">{{d}}</a>&nbsp;&nbsp;
                </li>
           </ul>

            <div class="list-group">
                {% for b in blogs %}
                  <ab href="{{url_for('main.blog_info', blog_id=b.id)}}" class="list-group-item ">
                    <h4 class="list-group-item-heading">
                        <a href={{url_for('main.blog_info', blog_id=b.id)}}">{{b.title}}</a>
                        <span style="float: right">
                        <a href="{{url_for('main.user_main_page', user_id=b.user.id)}}"> {{b.user.name}}</a>

                        &nbsp;&nbsp;{{b.time}}</span>
                    </h4>
                    <p class="list-group-item-text">
                        {{b.content[:200]}}
                    </p>
                  </ab>
                {% endfor %}
            </div>

        <div align="center">
            {% import 'page/macro.html' as macro %}
            {{macro.pagination_widget(pagination, 'main.index')}}
        </div>


{% endblock %}

bKProject/app/templates/main/user_info.html
{% extends 'base.html' %}

{% block content %}
    <h1><small>欢迎 &nbsp;</small>{{current_user.name}}</h1>
    <div class="row">
        <div class="col-md-3">
            <ul class="list-group">
                <li class="list-group-item list-group-item-success">昵称：{{current_user.name}}</li>
                <li class="list-group-item list-group-item-info">邮箱：{{current_user.email}}</li>
                <li class="list-group-item list-group-item-warning">角色：{{current_user.role.name}}</li>
                <li class="list-group-item list-group-item-danger">位置：
                    <a href="https://www.baidu.com/s?wd={{current_user.location}}">
                        {{current_user.location}}
                    </a>
                </li>
                <li class="list-group-item list-group-item-success">签名：{{current_user.label}}</li>
                <li class="list-group-item list-group-item-success">
                    粉丝<span class="badge">{{current_user.fensis.count()}}</span>
                </li>
                <li class="list-group-item list-group-item-success">
                    大V<span class="badge">{{current_user.davs.count()}}</span>
                </li>
                <li class="list-group-item list-group-item-success">
                    <a href="{{url_for('.mycollect')}}">我的收藏</a><span class="badge">{{current_user.collects.count()}}</span>
                </li>
            </ul>
            <a href="{{url_for('.edit_user')}}" class="btn btn-warning">编辑</a>
            <a href="{{url_for('.write_blog')}}" class="btn btn-info">发布信息</a>
        </div>
        <div class="col-md-9">
           <ul class="list-group">
                <li class="list-group-item list-group-item-success">昵称：{{current_user.name}}</li>
           </ul>

            <div class="list-group">
                {% for blog in pagination.items %}
                  <a href="{{url_for('main.blog_info', blog_id=blog.id)}}" class="list-group-item ">
                    <h4 class="list-group-item-heading">
                        {{blog.title}}<span style="float: right;"><small>{{blog.user.name}}&nbsp;&nbsp;{{blog.time}}</small></span>
                    </h4>
                    <p class="list-group-item-text">{{blog.content[:200]}}</p>
                  </a>
                {% endfor %}
            </div>

            <div align="center">
                {% import 'page/macro.html' as macro %}
                {{macro.pagination_widget(pagination, 'main.user_info')}}
            </div>
        </div>
    </div>



{% endblock %}

bKProject/app/templates/main/user_main_page.html
{% extends 'base.html' %}

{% block content %}
    <h1><small>欢迎 &nbsp;</small>{{current_user.name}}</h1>
    <div class="row">
        <div class="col-md-3">
            <ul class="list-group">
                <li class="list-group-item list-group-item-success">昵称：{{user.name}}</li>
                <li class="list-group-item list-group-item-info">邮箱：{{user.email}}</li>
                <li class="list-group-item list-group-item-warning">角色：{{user.role.name}}</li>
                <li class="list-group-item list-group-item-danger">位置：
                    <a href="https://www.baidu.com/s?wd={{current_user.location}}">
                        {{user.location}}
                    </a>
                </li>
                <li class="list-group-item list-group-item-success">签名：{{user.label}}</li>
            </ul>
            {% if user == current_user %}
            <a href="{{url_for('.edit_user')}}" class="btn btn-warning">编辑</a>
            {% endif %}
            &nbsp;&nbsp;
            {% if current_user.is_fensi_of(user) %}
                <a href="{{url_for('main.unfollow', user_id=user.id)}}" class="btn btn-default">
                <span style="font-size: 20px;color: red" class="glyphicon glyphicon-heart" aria-hidden="true">取关</span>
                </a>
            {% else %}
                &nbsp;
                <a href="{{url_for('main.follow', user_id=user.id)}}" class="btn btn-default">
                <span style="font-size: 20px;color: black"class="glyphicon glyphicon-heart-empty" aria-hidden="true">关注</span>
                </a>
            {% endif %}
        </div>
        <div class="col-md-9">
           <ul class="list-group">
                <li class="list-group-item list-group-item-success">昵称：{{current_user.name}}</li>
           </ul>

            <div class="list-group">
                {% for blog in pagination.items %}
                  <a href="{{url_for('main.blog_info', blog_id=blog.id)}}" class="list-group-item ">
                    <h4 class="list-group-item-heading">
                        {{blog.title}}<span style="float: right;"><small>{{blog.user.name}}&nbsp;&nbsp;{{blog.time}}</small></span>
                    </h4>
                    <p class="list-group-item-text">{{blog.content[:200]}}</p>
                  </a>
                {% endfor %}
            </div>

            <div align="center">
                {% import 'page/macro.html' as macro %}
                {{macro.pagination_widget_user_id(pagination, 'main.user_main_page', user.id)}}
            </div>
        </div>
    </div>



{% endblock %}

bKProject/app/templates/main/write_blog.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-10">
        <div style="border-bottom: 1px solid #d5d5d5">
            <div class="row">
                <form class="form-horizontal" method="post" action="">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        <label class="col-md-3 control-label">{{form.title.label}}</label>
                        <div class="col-md-9">
                            {{form.title(class="form-control")}}
                            {% for e in form.title.errors %}
                            <span style="color: red">{{e}}</span>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">{{form.content.label}}</label>
                        <div class="col-md-9">
                            {{form.content(class="form-control",style="height:400px")}}
                            {% for e in form.content.errors %}
                            <span style="color: red">{{e}}</span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-3 col-md-12">
                            {{form.submit(class="btn btn-success")}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}